spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/mrc
    username: root
    password: 24092001
  jpa:
    properties:
      hibernate:
        show_sql: true
        create_empty_composites:
          enabled: true
      format_sql: true
    open-in-view: false # disable this anti pattern
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hailylydk@gmail.com
    password: 24092001@Hl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#  quartz:
#    job-store-type: jdbc
#    properties:
#      org.quartz.threadPool.threadCount: 5
#      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  # Application config
application:
  enable-security: true # please be careful to use this value